### PR TITLE
Kicad enhance

### PR DESCRIPTION
**Pull request by realthunder**
Hi, 

First of all, thanks for the wonderful workbench you've brought us. This pull request consists of two commits. One is to enable auto part database population with KiCad import. The other is to use FreeCAD ImportGui for handling STEP colors. Further details can be found in the commit messages.

Regards
Zheng, Lei

### CODE REVIEW

**Comment by marmni** [comment]
Hi,
sorry for my late response - I do not received any mail that there is pull request. I check it as soon as possible. Thanks for help :).

**Comment by marmni** [comment]
Hi,
I used ImportGui.insert function but in different way, You forgot about col files - they are used to speeding up importing models to the FreeCAD.

I need to check yet auto model assignment for kicad_v4.

Thanks for help.

**Comment by marmni** [comment]
Hi,
I checked commits:
- Added auto model assignment for kicad_v4 
- Support loading of kicad parts with multiple models 
- Do not store auto extracted KiCAD model 

There are some differences between code in master FreeCAD-PCB branch and your (bug fixes/code updates). I need to implement your solutions (mentioned above) manually - I will try to do this in the next few days.

One more time - thanks for help :).

**Comment by luzpaz** [comment]
soft bump

**Comment by luzpaz** [comment]
@marmni ping

**Pull request closed without merging**
