### PR TITLE
Drop settings

### PR DESCRIPTION
**Pull request by gandy92**
The repo contains files that are written by the user with user settings, namely `PCBsettings.cfg` and `data/database.db`. It is debatable if more files from `data/` fall into this category.
This PR drops these files and adds them to .gitignore.
In case database.db is not created entirely from other data, another approach is called for.

### CODE REVIEW

**Comment by marmni** [comment]
Hi,
deleting file database.db is not a good idea. Settings saved there are connected with these models https://github.com/marmni/FreeCAD-PCB-library, so for person who downloads freecad-pcb for the first time, it is much easier to download extra files than to set everything from scratch.

**Comment by gandy92** [comment]
Yes, I can see that. I just stumbled over this after replacing the version FreeCAD installed with the git repository. After using the workbench, I realised several files from the repository got changed, including the two settings files.
I totally agree that a user should not be forced to start with no database at all. A possible solution could be to initialize the database from a template that resides in the registry. Another would be to have a user-database that extends the shipped database and resided in a separate file.
A few things to consider come to mind:
- When a developer uses the workbench and add entries to the database, what should be done with the database file? They could commit changes that may not apply to other users.
- What happens with the database changed by the user when the addon is updated by FreeCAD addon manager?
Just a few thoughts. I'll close the PR as it is not a preferable solution.

**Comment by marmni** [comment]
Hi,

-[...]When a developer uses the workbench and add entries to the database, what should be done with the database file? They could commit changes that may not apply to other users.[...]

This is implemented. First export database copy "Assign models -> Save database copy". After that import *.zip file "Assign models -> Import database"  (for example on the other computer). Script will filter imported data -> new models/already existing models in database.

-[...]What happens with the database changed by the user when the addon is updated by FreeCAD addon manager?[...]

That's why it is not recommended to keep database.db file under PCB folder (original position) - just somewhere else. Path to database.db is saved in freecad configs so this is not connected with any file in PCB folder.

**Comment by gandy92** [comment]
Thanks for pointing this out, I have missed this completely. I just started trying out the workbench by importing my eagle design, assigning a few models to packages, all easily doable trial and error style. I shall start digging into some documentation now.

**Pull request closed without merging**
